# Generated by Django 4.1.3 on 2022-12-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='retiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
