# Generated by Django 4.1.3 on 2022-11-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Retiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoLibro', models.IntegerField()),
                ('nombreAfiliado', models.CharField(max_length=50)),
                ('fechaRetiro', models.DateField()),
            ],
        ),
    ]
